"""Premium, non-breaking export planning layer.

This package does not replace the existing v4 exporters. It defines an
opt-in contract for high-value client deliverables: a deep report, a separate
presentation deck, evidence appendices, and QA gates.
"""

from .carbone import CarboneRenderError, render_premium_carbone_pdf, to_carbone_data
from .document import assemble_premium_report_document
from .docx import render_premium_docx
from .models import (
    PremiumAppendixSpec,
    PremiumAudience,
    PremiumBlockKind,
    PremiumDeckSlideSpec,
    PremiumDeliverableSpec,
    PremiumEvidenceRequirement,
    PremiumPage,
    PremiumPageType,
    PremiumPageVisual,
    PremiumPreparedBlock,
    PremiumPreparedSection,
    PremiumPublicationSpec,
    PremiumReportDocument,
    PremiumReportPlan,
    PremiumReportType,
    PremiumSectionSpec,
    PremiumVisualSpec,
    PremiumVisualType,
)
from .pdf import render_premium_pdf
from .planner import build_premium_report_plan
from .pptx import render_premium_pptx
from .readiness import PremiumReadiness, PremiumReadinessIssue, assess_premium_readiness
from .storyboard_quality import assess_premium_storyboard_quality
from .structured_source import (
    DEFAULT_REGENERATION_FORMATS,
    ReportActorRole,
    ReportArtifactFormat,
    ReportEditRequest,
    ReportQualityGateIssue,
    ReportQualityGateResult,
    ReportRegenerationPlan,
    ReportSourceMetadata,
    ReportVersionEntry,
    ResearchConnector,
    ResearchCoverage,
    StructuredReportBlock,
    StructuredReportSection,
    StructuredReportSource,
    StructuredReportSourceRef,
    StructuredReportVisual,
    apply_publication_remediation,
    apply_report_edits,
    build_regeneration_plan,
    create_report_version,
    final_report_from_structured_source,
    hash_structured_source,
    run_enterprise_quality_gates,
    structured_source_from_final_report,
)

__all__ = [
    "PremiumAppendixSpec",
    "PremiumAudience",
    "PremiumBlockKind",
    "PremiumDeckSlideSpec",
    "PremiumDeliverableSpec",
    "PremiumEvidenceRequirement",
    "PremiumPreparedBlock",
    "PremiumPreparedSection",
    "PremiumPublicationSpec",
    "PremiumPage",
    "PremiumPageType",
    "PremiumPageVisual",
    "PremiumVisualType",
    "PremiumReportDocument",
    "PremiumReportPlan",
    "PremiumReportType",
    "PremiumSectionSpec",
    "PremiumVisualSpec",
    "assemble_premium_report_document",
    "render_premium_docx",
    "render_premium_carbone_pdf",
    "render_premium_pdf",
    "render_premium_pptx",
    "to_carbone_data",
    "CarboneRenderError",
    "PremiumReadiness",
    "PremiumReadinessIssue",
    "assess_premium_readiness",
    "assess_premium_storyboard_quality",
    "build_premium_report_plan",
    "DEFAULT_REGENERATION_FORMATS",
    "ReportActorRole",
    "ReportArtifactFormat",
    "ReportEditRequest",
    "ReportQualityGateIssue",
    "ReportQualityGateResult",
    "ReportRegenerationPlan",
    "ReportSourceMetadata",
    "ReportVersionEntry",
    "ResearchConnector",
    "ResearchCoverage",
    "StructuredReportBlock",
    "StructuredReportSection",
    "StructuredReportSource",
    "StructuredReportSourceRef",
    "StructuredReportVisual",
    "apply_publication_remediation",
    "apply_report_edits",
    "build_regeneration_plan",
    "create_report_version",
    "final_report_from_structured_source",
    "hash_structured_source",
    "run_enterprise_quality_gates",
    "structured_source_from_final_report",
]
